apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: hello
          image: ghcr.io/alhossril/monolith:1.0.1
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.05
              memory: "10Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1